export { clamp } from './clamp'
export { getWall } from './getWall'
export { getWidth, getHeight } from './calcSize'
export { getFruit, getRandomFruit } from './getFruit'
export { getGuideLine, getGameOverLine, getGameOverGuideLine } from './line'
