export { default as Head } from './Head'
export { default as Content } from './Content'
export { default as Like } from './Like'
export { default as CommentPost } from './CommentPost'
export { default as Comments } from './Comments'
export { default as Footer } from './Footer'
