// import type { Metadata } from 'next'
import ThemeProvider from '@/components/Themes/Theme-provider'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from '@/components/Providers'
import { Header } from '@/components/Layout'
import LoginButton from '@/components/Button/Login'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className} id="__next">
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
            <LoginButton />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  )
}
