export enum Items {
  BLUEBERRY = 'BLUEBERRY',
  STRAWBERRY = 'STRAWBERRY',
  TANGERINE = 'TANGERINE',
  TOMATO = 'TOMATO',
  AVOCADO = 'AVOCADO',
  KOREANMELON = 'KOREANMELON',
  APPLE = 'APPLE',
  PEACH = 'PEACH',
  COCONUT = 'COCONUT',
  MELON = 'MELON',
  WATERMELON = 'WATERMELON',
  GOLDWATERMELON = 'GOLDWATERMELON',
}
