name: Auto-assign Issue and PR to Creator

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: "Auto-assign issue or PR to creator"
        uses: pozil/auto-assign-issue@v1
        with:
          assignees: ${{ github.actor }}
          repo-token: ${{ secrets.MOA_GITHUB_TOKEN }}
          allowSelfAssign: true
